title: One Data Cookie | SomeVizes
description: > # this means to ignore newlines until "baseurl:"
  One sweet path through the data world.
permalink: :title/
baseurl: # the subpath of your site, e.g. /blog
url: https://onedatacookie-somevizes.netlify.app/ # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Michal Koláček
author-img: michal-kolacek.png
digigarden: https://onedatacookie-digigarden.netlify.app/
social-github: one-data-cookie
social-medium: one-data-cookie
social-email: kolacek.m@gmail.com
social-linkedin: kolacekm
social-twitter: kolacekm

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: G-SZ1Z92MLNL # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 25
paginate_path: /page/:num

include: ["_pages"]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
